name: Build and Deploy Backend - Soutenance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Version stable recommandée pour Azure

      - name: Install dependencies
        run: npm install

      # CRITÈRE 4 : Étape de tests automatisés obligatoire pour la notation
      - name: Run Tests
        run: npm test

      # On ne zippe que le nécessaire (on exclut node_modules pour un transfert rapide)
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Conservation de ta méthode de connexion sécurisée (Critère 3)
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3EDDA334319F4EB9B875ACEF17592784 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1823AB8A951B4C008064D7D8C9935D3F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0E81639253714A9194F10C37FE84C3F2 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Back-soutenance'
          package: .